<?php
/**
 * AbbyyVantagePublicApiContractFieldType
 *
 * PHP version 5
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vantage processing REST API
 *
 * Environment: Production<br>Product Version: 1.0.0-0.37.11-20220624.1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace jpvdw86\AbbyVantage\Model;
use \jpvdw86\AbbyVantage\ObjectSerializer;

/**
 * AbbyyVantagePublicApiContractFieldType Class Doc Comment
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AbbyyVantagePublicApiContractFieldType
{
    /**
     * Possible values of this enum
     */
    const BARCODE = 'Barcode';
const CHECKMARK = 'Checkmark';
const CHECKMARK_GROUP = 'CheckmarkGroup';
const GROUP = 'Group';
const PICTURE = 'Picture';
const TEXT = 'Text';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BARCODE,
self::CHECKMARK,
self::CHECKMARK_GROUP,
self::GROUP,
self::PICTURE,
self::TEXT,        ];
    }
}
