<?php
/**
 * AbbyyVantagePublicApiContractTransactionsResultsClassificationDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vantage processing REST API
 *
 * Environment: Production<br>Product Version: 1.0.0-0.37.11-20220624.1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace jpvdw86\AbbyVantage\Model;

use \ArrayAccess;
use \jpvdw86\AbbyVantage\ObjectSerializer;

/**
 * AbbyyVantagePublicApiContractTransactionsResultsClassificationDto Class Doc Comment
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AbbyyVantagePublicApiContractTransactionsResultsClassificationDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Abbyy.Vantage.PublicApi.Contract.Transactions.Results.ClassificationDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'is_result_class_confident' => 'bool',
'result_class' => '\jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassDto',
'class_confidences' => '\jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassificationConfidenceDto[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'is_result_class_confident' => null,
'result_class' => null,
'class_confidences' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_result_class_confident' => 'isResultClassConfident',
'result_class' => 'resultClass',
'class_confidences' => 'classConfidences'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_result_class_confident' => 'setIsResultClassConfident',
'result_class' => 'setResultClass',
'class_confidences' => 'setClassConfidences'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_result_class_confident' => 'getIsResultClassConfident',
'result_class' => 'getResultClass',
'class_confidences' => 'getClassConfidences'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_result_class_confident'] = isset($data['is_result_class_confident']) ? $data['is_result_class_confident'] : null;
        $this->container['result_class'] = isset($data['result_class']) ? $data['result_class'] : null;
        $this->container['class_confidences'] = isset($data['class_confidences']) ? $data['class_confidences'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['is_result_class_confident'] === null) {
            $invalidProperties[] = "'is_result_class_confident' can't be null";
        }
        if ($this->container['result_class'] === null) {
            $invalidProperties[] = "'result_class' can't be null";
        }
        if ($this->container['class_confidences'] === null) {
            $invalidProperties[] = "'class_confidences' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets is_result_class_confident
     *
     * @return bool
     */
    public function getIsResultClassConfident()
    {
        return $this->container['is_result_class_confident'];
    }

    /**
     * Sets is_result_class_confident
     *
     * @param bool $is_result_class_confident is_result_class_confident
     *
     * @return $this
     */
    public function setIsResultClassConfident($is_result_class_confident)
    {
        $this->container['is_result_class_confident'] = $is_result_class_confident;

        return $this;
    }

    /**
     * Gets result_class
     *
     * @return \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassDto
     */
    public function getResultClass()
    {
        return $this->container['result_class'];
    }

    /**
     * Sets result_class
     *
     * @param \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassDto $result_class result_class
     *
     * @return $this
     */
    public function setResultClass($result_class)
    {
        $this->container['result_class'] = $result_class;

        return $this;
    }

    /**
     * Gets class_confidences
     *
     * @return \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassificationConfidenceDto[]
     */
    public function getClassConfidences()
    {
        return $this->container['class_confidences'];
    }

    /**
     * Sets class_confidences
     *
     * @param \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassificationConfidenceDto[] $class_confidences class_confidences
     *
     * @return $this
     */
    public function setClassConfidences($class_confidences)
    {
        $this->container['class_confidences'] = $class_confidences;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
