<?php
/**
 * AbbyyVantagePublicApiContractTransactionsResultsExtractedDocumentDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vantage processing REST API
 *
 * Environment: Production<br>Product Version: 1.0.0-0.37.11-20220624.1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace jpvdw86\AbbyVantage\Model;

use \ArrayAccess;
use \jpvdw86\AbbyVantage\ObjectSerializer;

/**
 * AbbyyVantagePublicApiContractTransactionsResultsExtractedDocumentDto Class Doc Comment
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AbbyyVantagePublicApiContractTransactionsResultsExtractedDocumentDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Abbyy.Vantage.PublicApi.Contract.Transactions.Results.ExtractedDocumentDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
'result_files' => '\jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsResultFileDto[]',
'classification' => '\jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassificationDto',
'business_rules_errors' => '\jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsDocumentBusinessRulesErrorDto[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'uuid',
'result_files' => null,
'classification' => null,
'business_rules_errors' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'result_files' => 'resultFiles',
'classification' => 'classification',
'business_rules_errors' => 'businessRulesErrors'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'result_files' => 'setResultFiles',
'classification' => 'setClassification',
'business_rules_errors' => 'setBusinessRulesErrors'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'result_files' => 'getResultFiles',
'classification' => 'getClassification',
'business_rules_errors' => 'getBusinessRulesErrors'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['result_files'] = isset($data['result_files']) ? $data['result_files'] : null;
        $this->container['classification'] = isset($data['classification']) ? $data['classification'] : null;
        $this->container['business_rules_errors'] = isset($data['business_rules_errors']) ? $data['business_rules_errors'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets result_files
     *
     * @return \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsResultFileDto[]
     */
    public function getResultFiles()
    {
        return $this->container['result_files'];
    }

    /**
     * Sets result_files
     *
     * @param \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsResultFileDto[] $result_files Will be empty for classification skill
     *
     * @return $this
     */
    public function setResultFiles($result_files)
    {
        $this->container['result_files'] = $result_files;

        return $this;
    }

    /**
     * Gets classification
     *
     * @return \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassificationDto
     */
    public function getClassification()
    {
        return $this->container['classification'];
    }

    /**
     * Sets classification
     *
     * @param \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsClassificationDto $classification classification
     *
     * @return $this
     */
    public function setClassification($classification)
    {
        $this->container['classification'] = $classification;

        return $this;
    }

    /**
     * Gets business_rules_errors
     *
     * @return \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsDocumentBusinessRulesErrorDto[]
     */
    public function getBusinessRulesErrors()
    {
        return $this->container['business_rules_errors'];
    }

    /**
     * Sets business_rules_errors
     *
     * @param \jpvdw86\AbbyVantage\Model\AbbyyVantagePublicApiContractTransactionsResultsDocumentBusinessRulesErrorDto[] $business_rules_errors business_rules_errors
     *
     * @return $this
     */
    public function setBusinessRulesErrors($business_rules_errors)
    {
        $this->container['business_rules_errors'] = $business_rules_errors;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
