<?php
/**
 * AbbyyVantagePublicApiContractCatalogsResultsReindexOperationResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vantage processing REST API
 *
 * Environment: Production<br>Product Version: 1.0.0-0.37.11-20220624.1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace jpvdw86\AbbyVantage;

/**
 * AbbyyVantagePublicApiContractCatalogsResultsReindexOperationResultTest Class Doc Comment
 *
 * @category    Class
 * @description AbbyyVantagePublicApiContractCatalogsResultsReindexOperationResult
 * @package     jpvdw86\AbbyVantage
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AbbyyVantagePublicApiContractCatalogsResultsReindexOperationResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AbbyyVantagePublicApiContractCatalogsResultsReindexOperationResult"
     */
    public function testAbbyyVantagePublicApiContractCatalogsResultsReindexOperationResult()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "index_model_id"
     */
    public function testPropertyIndexModelId()
    {
    }

    /**
     * Test attribute "workflow_processing_id"
     */
    public function testPropertyWorkflowProcessingId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "completed"
     */
    public function testPropertyCompleted()
    {
    }

    /**
     * Test attribute "current_state"
     */
    public function testPropertyCurrentState()
    {
    }
}
