<?php
/**
 * CatalogRecordsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vantage processing REST API
 *
 * Environment: Production<br>Product Version: 1.0.0-0.37.11-20220624.1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace jpvdw86\AbbyVantage;

use jpvdw86\AbbyVantage\Configuration;
use jpvdw86\AbbyVantage\ApiException;
use jpvdw86\AbbyVantage\ObjectSerializer;

/**
 * CatalogRecordsApiTest Class Doc Comment
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CatalogRecordsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addRecords
     *
     * Adds records to the specified catalog.
     *
     */
    public function testAddRecords()
    {
    }

    /**
     * Test case for deleteRecords
     *
     * Deletes the specified records from the catalog.
     *
     */
    public function testDeleteRecords()
    {
    }

    /**
     * Test case for getRecord
     *
     * Gets a record.
     *
     */
    public function testGetRecord()
    {
    }

    /**
     * Test case for getRecords
     *
     * Lists a portion of the records in the specified catalog.
     *
     */
    public function testGetRecords()
    {
    }
}
