<?php
/**
 * TransactionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Vantage processing REST API
 *
 * Environment: Production<br>Product Version: 1.0.0-0.37.11-20220624.1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace jpvdw86\AbbyVantage;

use jpvdw86\AbbyVantage\Configuration;
use jpvdw86\AbbyVantage\ApiException;
use jpvdw86\AbbyVantage\ObjectSerializer;

/**
 * TransactionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  jpvdw86\AbbyVantage
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransactionsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addFilesToTransaction
     *
     * Adds files to the transaction.
     *
     */
    public function testAddFilesToTransaction()
    {
    }

    /**
     * Test case for createTransaction
     *
     * Creates a processing transaction.
     *
     */
    public function testCreateTransaction()
    {
    }

    /**
     * Test case for deleteTransaction
     *
     * Deletes the transaction.
     *
     */
    public function testDeleteTransaction()
    {
    }

    /**
     * Test case for downloadFile
     *
     * Downloads the result files.
     *
     */
    public function testDownloadFile()
    {
    }

    /**
     * Test case for generateMobileInputLink
     *
     * Generates link to run mobile input with one time auth token to inject image to specific transaction.
     *
     */
    public function testGenerateMobileInputLink()
    {
    }

    /**
     * Test case for getTransactionInfo
     *
     * Gets transaction info.
     *
     */
    public function testGetTransactionInfo()
    {
    }

    /**
     * Test case for getTransactionRegistrationParameters
     *
     * Gets registration parameters for the transaction.
     *
     */
    public function testGetTransactionRegistrationParameters()
    {
    }

    /**
     * Test case for launchTransaction
     *
     * Starts processing of the files in new transaction.
     *
     */
    public function testLaunchTransaction()
    {
    }

    /**
     * Test case for startTransaction
     *
     * Starts the transaction.
     *
     */
    public function testStartTransaction()
    {
    }
}
